version: "3.1"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: [
      "bash", "-c",
      "./scripts/setup-wp.sh && \
       mkdir -p wp-content/ai1wm-backups wp-content/plugins/all-in-one-wp-migration/storage && \
       chown -R www-data:www-data wp-content/ai1wm-backups wp-content/plugins/all-in-one-wp-migration/storage && \
       chmod -R 755 wp-content/ai1wm-backups wp-content/plugins/all-in-one-wp-migration/storage && \
       php-fpm"
    ]
    environment:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - mysql_data:/var/lib/mysql

  wpcli:
    image: wordpress:cli
    # user: "33:33" # optional: match with www-data UID/GID
    # user: "${UID}:${GID}"
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./:/var/www/html
      - /home/serii/Documents/plugins-wp:/plugins
      - /home/serii/Downloads:/Downloads
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: wp

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "8085:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: root
  #   depends_on:
  #     - mysql
  #

volumes:
  mysql_data:

